from app.repositories.category_repository import CategoryRepository
from app.repositories.customer_repository import CustomerRepository
from app.repositories.product_repository import ProductRepository
from app.repositories.purchase_repository import PurchaseRepository
from app.repositories.sale_repository import SaleRepository
from app.repositories.stock_movement_repository import StockMovementRepository
from app.repositories.supplier_repository import SupplierRepository
from app.repositories.user_repository import UserRepository